### ISSUE TITLE
Brainstorm ideas for website

### ISSUE THREAD

**Issue by gigiguan** [gigiguan/flask_portfolio#1]
[Google Doc](https://docs.google.com/document/d/1GDL2P5qHNYJSxuEmO7BghdSnI1gzuHCjeGk1Jzixv_0/edit?usp=sharing)

**Comment by gigiguan** [comment]
outline created

**Comment by jm1021** [comment]
This seems like an outline for a brainstorm.  Perhaps adding wires would help
