### ISSUE TITLE
Week 7 Review

### ISSUE THREAD

**Issue by shrutiapcsp** [gigiguan/flask_portfolio#62]
**Self Grade:**
Shruti- 4/4 (color code)
Gigi- 4/4 (mutiply & divide shift, convert ascii to unicode)
Jessie- 4/4 (logic gates)
Neha- 4/4 (signed & unsigned addition)

Link to README video:

https://user-images.githubusercontent.com/89219435/136892439-be06031e-4375-4d63-95e6-f579b9a7101d.mp4

**Comment by gigiguan** [comment]
Link to evidence are in ReadME

**Comment by jm1021** [comment]
The project and participation across the board is impressive.   Nice job.  Scores as provided by Yolanda make sense to me.

My concerns are how little you spoke to code.  Also, your commits are all done at once.
